### ISSUE TITLE
Solve the duplicate links problem

### ISSUE THREAD

**Issue by Reflexe** [LMMS/bot#1]
CircleCI sends for some reason two status updates for every build. That has caused the "duplicate comments" problem with concurrent requests. However, right now it will just duplicate the links since the bot treats it as two different builds.  

The idea is to add a code footer with json representation of the comment and check for new updates instead of blindly adding more lines.

**Comment by tresf** [comment]
If it's of any help, you can use `<details>` tags to hide stuff... :D

<details><summary>:robot: Hey, I'm @LmmsBot and I made downloads for this pull request!</summary>
<p>
<details><summary>Debug information</summary>

```json
{
   "foo": "bar",
   "lorem": "ipsum",
   "timestamp": "2001-01-01"
}
```
</details>


### Windows

* **Windows 32-bit** (mingw): [`lmms-1.3.0-a1b2c3d.exe`](https://google.com)
* **Windows 64-bit** (mingw): [`lmms-1.3.0-a1b2c3d.exe`](https://google.com)

### Mac

* **macOS 10.13**: [`lmms-1.3.0-a1b2c3d.dmg`](https://google.com)

### Linux

* **Linux 64-bit** (AppImage) : [`lmms-1.3.0-a1b2c3d.AppImage`](https://google.com)
</p>
</details>
