### ISSUE TITLE
Add support for skipping the bot

### ISSUE THREAD

**Issue by tresf** [LMMS/bot#2]
Some PRs don't need a download, such as https://github.com/LMMS/lmms/pull/4884.  It would be nice to have the PR bot ignore certain builds.

Note @lukas-w also mentioned that the CI can be avoided directly by adding the keyword `[skip ci]` to the commit message, but I don't know who'd be thinking of that at PR time.

**Comment by Reflexe** [comment]
:) 
Fixed. 
use the `bot-skip` label for that.

**Comment by tresf** [comment]
Closed by https://github.com/LMMS/bot/commit/87687b3225b4a1839da59c40ffc898bbbeedbb10. (added for completeness sake)

**Comment by Reflexe** [comment]
Update: recommited without the mistake.
